/*
    Image Builder - Approach 1

    Objective:
    - Build the Python Selenium framework Docker image.
    - Push it to Docker Hub.

    This version is for your current Jenkins setup:
    - Jenkins controller runs in Docker.
    - Node1 is your Windows machine.
    - Therefore we use bat commands, not sh commands.

    Prerequisite in Jenkins:
    - Create username/password credential with id: dockerhub-creds
    - Update IMAGE_NAME if your Docker Hub repo name is different.

    Note:
    - Approach 1 uses docker login -p, which works but can show a warning.
    - Approach 2 is safer because it uses --password-stdin.
*/
pipeline {

    agent {
        node {
            label 'Node1'
            customWorkspace 'D:/Study/Mirror/CompleteMaterial-SDET/1.PythonSDET/3.SDET-Syllabus/10.DevOps/4.CI_CD_Docker_Grid_AWS/9.Project/docker_test/workspace'
        }
    }

    environment {
        IMAGE_NAME  = 'pratyushjindal123/python-selenium'
        IMAGE_TAG   = "${env.BUILD_NUMBER}"
        PROJECT_DIR = 'D:/Study/Mirror/CompleteMaterial-SDET/1.PythonSDET/3.SDET-Syllabus/10.DevOps/4.CI_CD_Docker_Grid_AWS/9.Project/docker_test/workspace/05-dockerize/python-selenium'
    }

    stages {

        stage('Validate Project') {
            steps {
                bat 'if not exist "%PROJECT_DIR%/Dockerfile" (echo Dockerfile not found at %PROJECT_DIR% && exit /b 1)'
                bat 'if not exist "%PROJECT_DIR%/requirements.txt" (echo requirements.txt not found at %PROJECT_DIR% && exit /b 1)'
            }
        }

        stage('Build Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% -t %IMAGE_NAME%:latest "%PROJECT_DIR%"'
            }
        }

        stage('Push Image') {
            environment {
                DOCKER_HUB = credentials('dockerhub-creds')
            }
            steps {
                bat 'docker login -u %DOCKER_HUB_USR% -p %DOCKER_HUB_PSW%'
                bat 'docker push %IMAGE_NAME%:%IMAGE_TAG%'
                bat 'docker push %IMAGE_NAME%:latest'
            }
        }
    }

    post {
        always {
            bat 'docker logout'
        }
    }
}
